spring:
    main:
        banner-mode: "off"
---
spring:
  profiles.active: dev
server:
    address: 0.0.0.0
    port: 9000

logging:
  file:
    name: ${PATH_LOGS}
  logback:
    rollingpolicy:
      file-name-pattern: Server-%d{yyyy-MM-dd}.log
      max-file-size: 10MB
